### ISSUE TITLE
Errors when updating taquito dependencies

### ISSUE THREAD

**Issue by tlacloc** [claudebarde/taquito-beacon-tutorial#11]
I tried to run the project with a newest version of taquito but I got an error when I try to build the application
```
/home/user/taquito-beacon-tutorial/node_modules/@taquito/beacon-wallet/dist/taquito-beacon-wallet.es6.js: /home/user/taquito-beacon-tutorial/node_modules/@taquito/beacon-wallet/dist/taquito-beacon-wallet.es6.js: Property name expected type of string but got undefined
    at validate (/home/user/taquito-beacon-tutorial/node_modules/@babel/types/lib/definitions/utils.js:159:13)
    at Object.validate (/home/user/taquito-beacon-tutorial/node_modules/@babel/types/lib/definitions/utils.js:228:7)
    at validateField (/home/user/taquito-beacon-tutorial/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (/home/user/taquito-beacon-tutorial/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at validateNode (/home/user/taquito-beacon-tutorial/node_modules/@babel/types/lib/builders/validateNode.js:16:27)
    at Object.identifier (/home/user/taquito-beacon-tutorial/node_modules/@babel/types/lib/builders/generated/index.js:432:36)
    at /home/user/taquito-beacon-tutorial/node_modules/regenerator-transform/lib/hoist.js:34:29
    at Array.forEach (<anonymous>)
    at varDeclToExpr (/home/user/taquito-beacon-tutorial/node_modules/regenerator-transform/lib/hoist.js:31:23)
    at exit (/home/user/taquito-beacon-tutorial/node_modules/regenerator-transform/lib/hoist.js:53:20)
    ```

**Comment by claudebarde** [comment]
Can you share your updated `package.json` file?

**Comment by tlacloc** [comment]
@claudebarde Sure, here it is!
```
{
  "name": "taquito-beacon-tutorial",
  "version": "1.0.0",
  "description": "Tutorial to create a Tezos dapp with Taquito and the Beacon SDK",
  "main": "index.js",
  "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html"
  },
  "keywords": [
    "tezos",
    "taquito",
    "beacon",
    "dapp"
  ],
  "author": "Claude Barde",
  "license": "MIT",
  "dependencies": {
    "@taquito/beacon-wallet": "^12.1.1",
    "@taquito/taquito": "^12.1.1",
    "babel-polyfill": "^6.26.0"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  }
}
```

**Comment by claudebarde** [comment]
The code is really old and after reviewing it, a few things don't work anymore as they used to, for example, the `TezosToolkit` instance from Taquito.
It doesn't make sense to me to maintain this code as I have published more recent articles that showcase how to use Beacon with Taquito, so I am going to archive this repo.
